app/routes/api.py
import os
from PIL import Image
import io

from app import db
from flask_login import current_user, login_required
from app.forms import PrivateInfoForm, PublicInfoForm
from app.models import Image, PrivateInfo, PublicInfo, User
from flask import Blueprint, abort, current_app, jsonify, redirect, request, send_file, send_from_directory, url_for

from werkzeug.utils import secure_filename

api = Blueprint('api', __name__,url_prefix='/api')

@api.route('/get_users')
def get_users():
    users = User.query.all()
    print('\n\n\n\n\n\n\n\n\n\n\n', users)
    user_list = [{'username': user.username, 'uid':user.uid , 'role': user.role} for user in users]
    return jsonify(user_list)


@api.route('/add_public_info', methods=['POST', 'GET'])
def add_public_info():
    form = PublicInfoForm()
    
    if form.validate_on_submit():
        uid = request.form.get('uid')
        public_info = PublicInfo.query.filter_by(user_uid=uid).first()
        
        if public_info:
            # Update the existing public_info record
            public_info.bio = form.bio.data
            public_info.name = form.name.data
            public_info.dob = form.dob.data
            public_info.gender = form.gender.data
            public_info.marital_status = form.marital_status.data
            public_info.occupation = form.occupation.data
            public_info.hobbies = form.hobbies.data
            public_info.caste = form.caste.data
            public_info.religion = form.religion.data
            public_info.education = form.education.data
            public_info.diet = form.diet.data
            public_info.mother_tongue = form.mother_tongue.data
            public_info.smoking_habits = form.smoking_habits.data
            public_info.alcohol_intake = form.alcohol_intake.data
        else:
            # Create a new public_info record
            public_info = PublicInfo(
                bio=form.bio.data,
                name=form.name.data,
                dob=form.dob.data,
                gender=form.gender.data,
                marital_status=form.marital_status.data,
                occupation=form.occupation.data,
                hobbies=form.hobbies.data,
                caste=form.caste.data,
                religion=form.religion.data,
                education=form.education.data,
                diet=form.diet.data,
                mother_tongue=form.mother_tongue.data,
                smoking_habits=form.smoking_habits.data,
                alcohol_intake=form.alcohol_intake.data,
                user_uid=uid
            )
            db.session.add(public_info)

        db.session.commit()
        
        # Redirect based on user role
        if current_user.role == 'admin':
            return redirect(url_for('admin.users'))
        elif current_user.role == 'user':
            return redirect(url_for('main.profile'))



@api.route('/upload_profile_pic', methods=['POST'])
def upload_profile_pic():
    if 'image' not in request.files:
        return jsonify(success=False, error="No image part"), 400
    
    file = request.files['image']
    if file.filename == '':
        return jsonify(success=False, error="No selected file"), 400

    # Check if the file has an allowed extension
    ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
    def allowed_file(filename):
        return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file_ext = filename.rsplit('.', 1)[1].lower()
        
        # Set the filename to profilepic with the correct extension
        new_filename = f"profilepic.{file_ext}"

        # Define the path to the user's folder
        user_folder = os.path.join(current_app.config['UPLOAD_FOLDER'], current_user.uid, 'profilepic')

        # Create the folder if it doesn't exist
        if not os.path.exists(user_folder):
            os.makedirs(user_folder)

        # Save the file, replacing the old profile picture
        file_path = os.path.join(user_folder, new_filename)
        file.save(file_path)

        return jsonify(success=True), 200

    return jsonify(success=False, error="File type not allowed"), 400


@api.route('/get_profile_pic/<uid>')
def get_profile_pic(uid):
    user_folder = os.path.join(current_app.config['UPLOAD_FOLDER'], uid, 'profilepic')
    
    # Look for profilepic with any of the allowed extensions
    for ext in ['jpg', 'jpeg', 'png', 'gif']:
        file_path = os.path.join(user_folder, f"profilepic.{ext}")
        if os.path.exists(file_path):
            return send_from_directory(user_folder, f"profilepic.{ext}")
    
    # If no profile picture is found, return nothing
    # abort(204)
    return send_from_directory('static','uploads/default_profile.png'), 404


@api.route('/delete_profile_pic', methods=['POST'])
@login_required
def delete_profile_pic():
    user_folder = os.path.join(current_app.config['UPLOAD_FOLDER'], current_user.uid, 'profilepic')
    filename = 'profilepic'  # Fixed filename for the profile picture

    # Check for file extensions
    file_extensions = ['jpg', 'jpeg', 'png', 'gif']
    file_deleted = False

    for ext in file_extensions:
        file_path = os.path.join(user_folder, f"{filename}.{ext}")
        if os.path.exists(file_path):
            os.remove(file_path)
            file_deleted = True
            break  # Exit loop once the file is deleted

    if file_deleted:
        return jsonify(success=True), 200
    else:
        return jsonify(success=False, error="Profile picture not found"), 404
    
    
    


@api.route('/upload_image', methods=['POST'])
@login_required
def upload_image():
    if 'image' not in request.files:
        return jsonify({'error': 'No file part'}), 400
    
    file = request.files['image']
    
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400
    
    if len(current_user.images) >= 5:
        return jsonify({'error': 'You can only upload up to 5 images'}), 400
    
    if file:
        # Secure the filename and retain its extension
        filename = secure_filename(file.filename)
        extension = os.path.splitext(filename)[1].lower()
        
        # Ensure the extension is one of the allowed image formats
        if extension not in ['.jpg', '.jpeg', '.png', '.gif']:
            return jsonify({'error': 'Unsupported image format'}), 400
        
        user_folder = os.path.join(current_app.config['UPLOAD_FOLDER'], current_user.uid)
        
        if not os.path.exists(user_folder):
            os.makedirs(user_folder)
        
        file_path = os.path.join(user_folder, filename)
        try:
            # Save the file with the original extension
            file.save(file_path)
            new_image = Image(uid=current_user.uid, filename=filename, file_path=file_path)
            db.session.add(new_image)
            db.session.commit()
            
            return jsonify({
                'success': 'Image uploaded successfully',
                'id': new_image.id,
                'url': url_for('api.get_image', uid=current_user.uid, filename=filename)
            }), 200
        except Exception as e:
            return jsonify({'error': 'Failed to upload image', 'message': str(e)}), 500
    
    return jsonify({'error': 'Failed to upload image'}), 500

@api.route('/get_images/<uid>', methods=['GET'])
@login_required
def get_images(uid):
    user_folder = os.path.join(current_app.config['UPLOAD_FOLDER'], uid)
    
    if not os.path.exists(user_folder):
        return jsonify({'error': 'User folder does not exist'}), 404
    
    image_files = []
    try:
        for filename in os.listdir(user_folder):
            if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.gif')):
                image_files.append(url_for('api.get_image', uid=uid, filename=filename, _external=True))
    except Exception as e:
        return jsonify({'error': 'Failed to retrieve images', 'message': str(e)}), 500
    
    return jsonify({'images': image_files}), 200


@api.route('/get_image/<uid>/<filename>', methods=['GET'])
@login_required
def get_image(uid, filename):
    user_folder = os.path.join(current_app.config['UPLOAD_FOLDER'], uid)
    file_path = os.path.join(user_folder, filename)
    
    if os.path.exists(file_path):
        # Determine MIME type based on file extension
        mime_type = None
        
        if filename.lower().endswith('.png'):
            mime_type = 'image/png'
        elif filename.endswith('.jpg') or filename.endswith('.jpeg'):
            mime_type = 'image/jpeg'
        elif filename.endswith('.gif'):
            mime_type = 'image/gif'
        
        if mime_type:
            return send_file(file_path, mimetype=mime_type)
    
    return jsonify({'error': 'Image not found'}), 404

app/routes/auth.py
from datetime import datetime
import os
from flask import Blueprint, current_app, flash, render_template, url_for
from flask import redirect
from flask_login import current_user, login_user, logout_user

from app.forms import LoginForm, SignupForm
from app.models import AdminLog, User
from app.extensions import db, socketio

auth = Blueprint('auth', __name__, url_prefix='/auth')


########## Admin
@auth.route('/admin_login', methods = ['GET','POST'])
def admin_login():
    if current_user.is_authenticated:
        return redirect(url_for('admin.index'))
    
    form = LoginForm()
    if form.validate_on_submit():
        logusername = form.logusername.data
        logpassword = form.logpassword.data

        user = User.query.filter_by(username=logusername).first()
        if user and user.check_password(logpassword) and user.role=='admin':
            if user.is_logged_in:
                flash('User is already logged in from another device.', 'danger')
                return redirect(url_for('auth.admin_login'))

            login_user(user)
            user.is_logged_in = True
            log_entry = AdminLog(uid=user.uid, username=user.username, role='admin', login_time=datetime.now())
            db.session.add(log_entry)
            db.session.commit()
            
            socketio.emit('user_logged_in', {
                'uid': user.uid,
                'username': user.username,
                'role': 'admin',
                'login_time': log_entry.login_time.strftime('%Y-%m-%d %H:%M:%S')
            })
        
            return redirect(url_for('admin.index'))
        
        flash('Invalid username or password', 'danger')

    return render_template('admin/admin_auth.html', login_form=form, signup_form=SignupForm())


@auth.route('/admin_signup', methods=['GET','POST'])
def admin_signup():
    if current_user.is_authenticated:
        return redirect(url_for('admin.index'))
    
    form = SignupForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = User.query.filter_by(username=username).first()
        if user:
            flash('Username already exists', 'danger')
            return redirect(url_for('auth.admin_login'))

        new_user = User(username=username)
        new_user.set_password(password)
        new_user.generate_uid()

        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        new_user.is_logged_in = True

        log_entry = AdminLog(uid=new_user.uid, username=new_user.username, role='admin', login_time=datetime.now())
        db.session.add(log_entry)
        db.session.commit()
        
        # Create directory for the new user
        user_folder = os.path.join(current_app.config['UPLOAD_FOLDER'], new_user.uid)
        os.makedirs(user_folder, exist_ok=True)
         
        socketio.emit('user_logged_in', {
                'uid': new_user.uid,
                'username': new_user.username,
                'role': 'admin',
                'login_time': log_entry.login_time.strftime('%Y-%m-%d %H:%M:%S')
            })

        return redirect(url_for('admin.index'))

    return render_template('admin/admin_auth.html', login_form=LoginForm(), signup_form=form)


@auth.route('/admin_logout')
def admin_logout():
    if current_user.is_authenticated:
        log_entry = AdminLog.query.filter_by(uid=current_user.uid).order_by(AdminLog.id.desc()).first()
        if log_entry and log_entry.logout_time is None:
            log_entry.logout_time = datetime.now()  # Record current time
            db.session.commit()
        socketio.emit('user_logged_out', {
                'uid': current_user.uid,
                'logout_time': log_entry.logout_time.strftime('%Y-%m-%d %H:%M:%S')
            })
    current_user.is_logged_in = False
    logout_user()
    db.session.commit()

    return redirect(url_for('admin.admin_auth'))


############# User
@auth.route('/login', methods = ['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    
    form = LoginForm()
    if form.validate_on_submit():
        logusername = form.logusername.data
        logpassword = form.logpassword.data

        user = User.query.filter_by(username=logusername).first()
        if user and user.check_password(logpassword):
            if user.is_logged_in:
                flash('User is already logged in from another device.', 'danger')
                return redirect(url_for('main.index'))

            login_user(user)
            user.is_logged_in = True
            db.session.commit()
            
        
            return redirect(url_for('main.index'))
        
        flash('Invalid username or password', 'danger')

    return render_template('main/index.html', login_form=form, signup_form=SignupForm())


@auth.route('/signup', methods=['GET','POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    
    form = SignupForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = User.query.filter_by(username=username).first()
        if user:
            flash('Username already exists', 'danger')
            return redirect(url_for('main.index'))

        new_user = User(username=username, role='user')
        new_user.set_password(password)
        new_user.generate_uid()

        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        new_user.is_logged_in = True

        db.session.commit()
        
        # Create directory for the new user
        user_folder = os.path.join(current_app.config['UPLOAD_FOLDER'], new_user.uid)
        os.makedirs(user_folder, exist_ok=True)

        return redirect(url_for('main.index'))

    return render_template('main/index.html', login_form=LoginForm(), signup_form=form)


@auth.route('/logout')
def logout():
    current_user.is_logged_in = False
    logout_user()
    db.session.commit()
    return redirect(url_for('main.index'))


########### Data Entry
@auth.route('/data_entry_login', methods = ['GET','POST'])
def data_entry_login():
    if current_user.is_authenticated:
        return redirect(url_for('data_enrty.index'))
    
    form = LoginForm()
    if form.validate_on_submit():
        logusername = form.logusername.data
        logpassword = form.logpassword.data

        user = User.query.filter_by(username=logusername).first()
        if user and user.check_password(logpassword):
            if user.is_logged_in:
                flash('User is already logged in from another device.', 'danger')
                return redirect(url_for('data_enrty.index'))

            login_user(user)
            user.is_logged_in = True
            db.session.commit()
            
        
            return redirect(url_for('main.index'))
        
        flash('Invalid username or password', 'danger')

    return render_template('dataentry/index.html', login_form=form, signup_form=SignupForm())


@auth.route('/data_entry_signup', methods=['GET','POST'])
def data_entry_signup():
    if current_user.is_authenticated:
        return redirect(url_for('data_entry.index'))
    
    form = SignupForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = User.query.filter_by(username=username).first()
        if user:
            flash('Username already exists', 'danger')
            return redirect(url_for('data_entry.index'))

        new_user = User(username=username, role='data entry')
        new_user.set_password(password)
        new_user.generate_uid()

        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        new_user.is_logged_in = True

        db.session.commit()
        
        # # Create directory for the new user
        # user_folder = os.path.join(current_app.config['UPLOAD_FOLDER'], new_user.uid)
        # os.makedirs(user_folder, exist_ok=True)

        return redirect(url_for('data_entry.index'))

    return render_template('dataentry/index.html', login_form=LoginForm(), signup_form=form)


@auth.route('/data_entry_logout')
def data_entry_logout():
    logout_user()
    return redirect(url_for('data_entry.index'))

app/routes/dataentry.py
from flask_login import login_required
from app.forms import CreateUserForm, LoginForm, PublicInfoForm, SignupForm
from flask import Blueprint, render_template, redirect, url_for

from app.models import User

data_entry = Blueprint('data_entry', __name__, url_prefix='/data_entry')

@login_required
@data_entry.route('/index')
def index():
    login_form = LoginForm()
    signup_form = SignupForm()
    form = PublicInfoForm()
    createuser = CreateUserForm()
    users = User.query.all()
    return render_template('data_entry/index.html', users=users, form=form, createuser=createuser, login_form=login_form, signup_form=signup_form)

app/templates/data_entry/index.html
{% extends 'data_entry/base.html' %}

{% block content %}
    {% if not current_user.is_authenticated %}
        <div class="container">
            <h2>Data Entry Login</h2>
            <hr>
            <!-- Sign In Form -->
            <form method="POST" action="{{ url_for('auth.data_entry_login') }}">
                {{ login_form.hidden_tag() }}
                <h3>Sign In</h3>
                <div class="form-group">
                    {{ login_form.logusername.label }}<br>
                    {{ login_form.logusername(size=32, class="form-control") }}
                </div>
                <div class="form-group">
                    {{ login_form.logpassword.label }}<br>
                    {{ login_form.logpassword(size=32, class="form-control") }}
                </div>
                <div class="form-group">
                    {{ login_form.logsubmit(class="btn btn-primary") }}
                </div>
            </form>
        
            <hr>
            <!-- Sign Up Form -->
            <form method="POST" action="{{ url_for('auth.data_entry_signup') }}">
                {{ signup_form.hidden_tag() }}
                <h3>Sign Up</h3>
                <div class="form-group">
                    {{ signup_form.username.label }}<br>
                    {{ signup_form.username(size=32, class="form-control") }}
                </div>
                <div class="form-group">
                    {{ signup_form.password.label }}<br>
                    {{ signup_form.password(size=32, class="form-control") }}
                </div>
                <div class="form-group">
                    {{ signup_form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    {% endif %}

    
    <!-- New User creation button and modal -->
    <div class="container">
        <!-- Create User Button -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createUserModal">
            Create User
        </button>

        <!-- Create User Modal -->
        <div class="modal fade" id="createUserModal" tabindex="-1" aria-labelledby="createUserModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="createUserModalLabel">Create User</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" action="{{ url_for('admin.add_user') }}">
                            {{ createuser.hidden_tag() }}
                            <div class="form-group">
                                {{ createuser.username.label(class="form-label") }}
                                {{ createuser.username(class="form-control") }}
                            </div>
                            <div class="form-group">
                                {{ createuser.password.label(class="form-label") }}
                                {{ createuser.password(class="form-control") }}
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- Display existing users -->
        <table id="users-table" class="table table-striped table-bordered mt-3 text-nowrap">
            <thead class="thead-dark">
                <tr>
                    <th>Uid</th>
                    <th>Username</th>
                    <th>Role</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ user.uid }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.role }}</td>
                    <td>
                        {% if user != current_user %}
                            <!-- Edit Role Button -->
                            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#editRoleModal{{ user.uid }}">
                                Edit Role
                            </button>

                            <!-- Edit Role Modal -->
                            <div class="modal fade" id="editRoleModal{{ user.uid }}" tabindex="-1" aria-labelledby="editRoleModalLabel{{ user.uid }}" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="editRoleModalLabel{{ user.uid }}">Edit Role for {{ user.username }}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form method="POST" action="{{ url_for('admin.edit_user', uid=user.uid) }}">
                                                <div class="form-group">
                                                    <label for="role{{ user.uid }}" class="form-label">New Role</label>
                                                    <input type="text" id="role{{ user.uid }}" name="role" class="form-control" value="{{ user.role }}">
                                                </div>
                                                <div class="form-group">
                                                    <button type="submit" class="btn btn-primary">Save</button>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Add public info button -->
                            <button class="btn btn-info btn-sm" data-toggle="modal" data-target="#addPublicInfoModal" data-uid="{{ user.uid }}">Add Public Data</button>
                            <!-- Add Public Info Modal -->
                            <div class="modal fade" id="addPublicInfoModal" tabindex="-1" role="dialog" aria-labelledby="addPublicInfoModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="addPublicInfoModalLabel">Add Public Info</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form id="addPublicInfoForm" method="POST" action="{{ url_for('api.add_public_info') }}">
                                                <div class="form-group">
                                                    {{ form.name.label }} {{ form.name(class="form-control") }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.dob.label }} {{ form.dob(class="form-control") }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.gender.label }} {{ form.gender(class="form-control") }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.marital_status.label }} {{ form.marital_status(class="form-control") }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.occupation.label }} {{ form.occupation(class="form-control") }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.hobbies.label }} {{ form.hobbies(class="form-control") }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.caste.label }} {{ form.caste(class="form-control") }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.religion.label }} {{ form.religion(class="form-control") }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.education.label }} {{ form.education(class="form-control") }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.diet.label }} {{ form.diet(class="form-control") }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.mother_tongue.label }} {{ form.mother_tongue(class="form-control") }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.smoking_habits.label }} {{ form.smoking_habits() }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form.alcohol_intake.label }} {{ form.alcohol_intake() }}
                                                </div>
                                                <input type="hidden" id="user_uid" name="user_uid">
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-primary">Save changes</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            Action Unavailable
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


        
    </div>

    <!-- Add new user, add user public info -->
    <script>
        $(document).ready(function() {
            $('#addPublicInfoModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget);
                var uid = button.data('uid');
                
                var modal = $(this);
                modal.find('#user_uid').val(uid);
            });

            $('#addPublicInfoForm').on('submit', function (event) {
                event.preventDefault();
                
                $.ajax({
                    url: $(this).attr('action'),
                    method: 'POST',
                    data: $(this).serialize(),
                    success: function (response) {
                        alert('Public info added successfully');
                        $('#addPublicInfoModal').modal('hide');
                        location.reload();
                    },
                    error: function (xhr, status, error) {
                        alert('Error: ' + error);
                    }
                });
            });
        });
    </script>

{% endblock %}